require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImageTestsController do

  # This should return the minimal set of attributes required to create a valid
  # ImageTest. As you add validations to ImageTest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all image_tests as @image_tests" do
      image_test = ImageTest.create! valid_attributes
      get :index
      assigns(:image_tests).should eq([image_test])
    end
  end

  describe "GET show" do
    it "assigns the requested image_test as @image_test" do
      image_test = ImageTest.create! valid_attributes
      get :show, :id => image_test.id.to_s
      assigns(:image_test).should eq(image_test)
    end
  end

  describe "GET new" do
    it "assigns a new image_test as @image_test" do
      get :new
      assigns(:image_test).should be_a_new(ImageTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested image_test as @image_test" do
      image_test = ImageTest.create! valid_attributes
      get :edit, :id => image_test.id.to_s
      assigns(:image_test).should eq(image_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImageTest" do
        expect {
          post :create, :image_test => valid_attributes
        }.to change(ImageTest, :count).by(1)
      end

      it "assigns a newly created image_test as @image_test" do
        post :create, :image_test => valid_attributes
        assigns(:image_test).should be_a(ImageTest)
        assigns(:image_test).should be_persisted
      end

      it "redirects to the created image_test" do
        post :create, :image_test => valid_attributes
        response.should redirect_to(ImageTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved image_test as @image_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImageTest.any_instance.stub(:save).and_return(false)
        post :create, :image_test => {}
        assigns(:image_test).should be_a_new(ImageTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImageTest.any_instance.stub(:save).and_return(false)
        post :create, :image_test => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested image_test" do
        image_test = ImageTest.create! valid_attributes
        # Assuming there are no other image_tests in the database, this
        # specifies that the ImageTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImageTest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => image_test.id, :image_test => {'these' => 'params'}
      end

      it "assigns the requested image_test as @image_test" do
        image_test = ImageTest.create! valid_attributes
        put :update, :id => image_test.id, :image_test => valid_attributes
        assigns(:image_test).should eq(image_test)
      end

      it "redirects to the image_test" do
        image_test = ImageTest.create! valid_attributes
        put :update, :id => image_test.id, :image_test => valid_attributes
        response.should redirect_to(image_test)
      end
    end

    describe "with invalid params" do
      it "assigns the image_test as @image_test" do
        image_test = ImageTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImageTest.any_instance.stub(:save).and_return(false)
        put :update, :id => image_test.id.to_s, :image_test => {}
        assigns(:image_test).should eq(image_test)
      end

      it "re-renders the 'edit' template" do
        image_test = ImageTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImageTest.any_instance.stub(:save).and_return(false)
        put :update, :id => image_test.id.to_s, :image_test => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested image_test" do
      image_test = ImageTest.create! valid_attributes
      expect {
        delete :destroy, :id => image_test.id.to_s
      }.to change(ImageTest, :count).by(-1)
    end

    it "redirects to the image_tests list" do
      image_test = ImageTest.create! valid_attributes
      delete :destroy, :id => image_test.id.to_s
      response.should redirect_to(image_tests_url)
    end
  end

end
